
site_name: Sample API Docs
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
plugins:
  - search
  - openapi

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight

nav:
  - Home: index.md
  - Introduction: intro.md
  - API Reference: api.md
